### ISSUE TITLE
try-catch 设置不合理导致异常断点 All Objective-C Exceptions 几乎无法工作

### ISSUE THREAD

**Issue by Navimark** [ThinkingDataAnalytics/ios-sdk#2]
问题版本：2.6.5
问题描述：`NSDictionary+TDJsonOutput.m` 中存在的`descriptionWithLocale:`方法，通过`try-catch` 粗鲁地将字典转换成 json ，这种 category hook 会全局起作用，一旦字典数据不合法导致 json 转换失败，就会被 try-catch 命中，进而触发工程中添加的 `All Objective-C Exceptions` 异常断点。大型工程中字典数据类型、格式繁多，实际开发中很容易就会被这里的断点命中，导致全局异常断点几乎无法正常工作，非常影响工作效率。

**如果是 SDK 需要用到，请将生效范围局限在自己的 SDK 内部，停止在全局范围内造成影响**

问题现场附图：
![image](https://user-images.githubusercontent.com/4392747/119486877-4e7f4700-bd8b-11eb-9a91-b73681206a9a.png)

**Comment by ihuangdiao** [comment]
你好，我们已经关注到这个问题，将会在下个版本修复。谢谢你的反馈！
